version: '3'

services:

  database:
    image: postgres
    hostname: testdb
    container_name: testdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: privattestdb
    restart: unless-stopped
    networks:
      - backend

networks:
  backend: